name: Local Terraform Kind Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'kind/**'                             # Check for changes in the kind directory
      - '.github/workflows/kind-deploy.yaml'   # Check for changes in the workflow file
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  # 1. Reusable GitLeak workflow call
  gitleaks-scan:
    name: GitLeak Scan
    uses: ./.github/workflows/gitleaks.yaml

  # 2. Kind Deployment Job
  kind-deploy:
    needs: gitleaks-scan   # 👈 Gitleaks pass
    name: Kind DevOps Cluster Deployment
    runs-on: self-hosted    # sachin-pc runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Terraform Init
        run: terraform init
        working-directory: kind

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy --auto-approve
          else
            terraform apply --auto-approve
          fi
        working-directory: kind

      - name: Verify Pods
        id: destroy-step
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "status=🚀 Local DevOps Cluster Destroyed Successfully!!" >> $GITHUB_OUTPUT
          else
            kubectl get pods -A
            echo "status=🚀 Local DevOps Cluster Deployed Successfully!!" >> $GITHUB_OUTPUT
          fi

      - name: Publish Summary to GitHub Actions
        run: |
          echo "### 🚀 Local DevOps Cluster ${{ steps.destroy-step.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "#### 🔗 Access Endpoints:" >> $GITHUB_STEP_SUMMARY
          echo "| Service | URL / Port | Credentials |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| **ArgoCD** | \`https://localhost:8086\` | User: \`admin\` |" >> $GITHUB_STEP_SUMMARY
          echo "| **Vault** | \`https://localhost:8087\` | User: \`admin\` / Pass: \`root\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### 🛠️ Useful Commands:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Get ArgoCD Password:" >> $GITHUB_STEP_SUMMARY
          echo "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d && echo" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY