name: Local Terraform Kind Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: kind # terraform working directory for kind deployment

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: kind

      - name: Verify Pods
        run: kubectl get pods -A